"""Event 3 — afterFileEdit: tests for post-edit.py.

Skipped until post-edit.py is ported to .cursor/hooks/scripts/.
"""

import pytest


@pytest.mark.skip(reason="post-edit.py not yet ported to .cursor/hooks/scripts/")
class TestPostEdit:
    def test_python_file_triggers_ruff_check(self) -> None: ...
    def test_non_python_file_skips_ruff(self) -> None: ...
    def test_ruff_never_runs_fix_flag(self) -> None: ...
    def test_missing_file_path_does_not_crash(self) -> None: ...
    def test_empty_event_does_not_crash(self) -> None: ...
    def test_event_logged_to_events_jsonl(self) -> None: ...
    def test_multiple_edits_counted_independently(self) -> None: ...
    def test_language_detection_python(self) -> None: ...
    def test_language_detection_typescript(self) -> None: ...
    def test_language_detection_unknown_extension(self) -> None: ...
