"""Event 4 — stop: tests for stop.py.

Skipped until stop.py is ported to .cursor/hooks/scripts/.
"""

import pytest


@pytest.mark.skip(reason="stop.py not yet ported to .cursor/hooks/scripts/")
class TestStop:
    def test_mixed_events_aggregated_correctly(self) -> None: ...
    def test_empty_events_file_produces_zero_counts(self) -> None: ...
    def test_missing_events_file_does_not_crash(self) -> None: ...
    def test_only_matching_conversation_counted(self) -> None: ...
    def test_malformed_lines_skipped(self) -> None: ...
    def test_language_other_excluded_from_summary(self) -> None: ...
    def test_status_passed_through_to_summary(self) -> None: ...
    def test_session_summary_written_to_sessions_dir(self) -> None: ...
    def test_gate_1_failed_on_error_status(self) -> None: ...
    def test_gate_2_success_on_completion_markers(self) -> None: ...
    def test_gate_3_abandoned_on_short_session(self) -> None: ...
    def test_gate_4_unknown_on_ambiguous_signals(self) -> None: ...
